# vim: ft=python
env = SConscript('../esoebuild/scons/env.py')
conf = Configure(env)

Export('env')
Export('conf')

libs = SConscript('../esoebuild/scons/libs.py')
libs.openssl_lib()
libs.curl_lib()
libs.asio_lib()
libs.icu_lib()
libs.xerces_lib()
libs.xml_security_lib()
libs.xsd_lib()
libs.boost_libs()
libs.esoe_saml_lib()
libs.esoe_spep_lib()

if env.get('PLATFORM') == 'win32':
	conf.CheckLib('advapi32')
env = conf.Finish()

Repository('src')
sources = [env.Glob(path) for path in Split("""
	*.cpp
""")]

env.Program('spepd', sources)
