/*
 * Copyright 2006-2007, Queensland University of Technology
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not 
 * use this file except in compliance with the License. You may obtain a copy of 
 * the License at 
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * Author: Bradley Beddoes
 * Creation Date: 12/01/2007
 * 
 * Purpose: Handlers errors which may be generated by Xerces in the document validation stage
 */
 
#ifndef SAML2ERRORHANDLER_H_
#define SAML2ERRORHANDLER_H_

/* Xerces */
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/dom/DOMError.hpp>

XERCES_CPP_NAMESPACE_USE

namespace saml2
{
	class SAML2ErrorHandler : public DOMErrorHandler
	{
		public:
			
			/*
			 * Called when error state encountered in parsing operations
			 * 
			 * @exception SAXException Thrown to halt further processing by the DOMBuilder class
			 */			
			bool handleError (const DOMError &domError);
	};
}

#endif /*SAML2ERRORHANDLER_H_*/
