/*
 * Copyright 2006-2007, Queensland University of Technology
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not 
 * use this file except in compliance with the License. You may obtain a copy of 
 * the License at 
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * Author: Bradley Beddoes
 * Creation Date: 12/01/2007
 * 
 * Purpose: Handlers errors which may be generated by Xerces in the document validation stage
 */

/* Xerces */
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/dom/DOMError.hpp>
#include <xercesc/sax/SAXParseException.hpp>

/* Local Codebase */
#include "handlers/SAML2ErrorHandler.h"

XERCES_CPP_NAMESPACE_USE

namespace saml2
{	
	bool SAML2ErrorHandler::handleError (const DOMError &domError)
	{
		/* While handleError does not explicity state it will throw and exception as of Xerces 2.7
		 * it has been implemented here so that parsing errors will successfully terminate DOMBuilder,
		 * furthermore DOMBuilder::parse() does state that it will return a SAXException on certain
		 * errors which is why a more general exception was not defined for this case.
		 * 
		 * This may need to be revisted in future versions.
		 */
		throw SAXException(domError.getMessage());
	}
}
