# vim: ft=python
env = SConscript('../esoebuild/scons/env.py')
conf = Configure(env)

Export('env')
Export('conf')

libs = SConscript('../esoebuild/scons/libs.py')
libs.check_boost_libs()
libs.check_xsd_lib()

env = conf.Finish()

paths = Split("""
	saml2/resolver/*.cpp
	saml2/identifier/*.cpp
	saml2/logging/*.cpp
	saml2/validator/*.cpp
	saml2/handlers/*.cpp
	saml2/xsd/*.cpp
	saml2/exceptions/*.cpp
	saml2/namespace/*.cpp
	saml2/bindings/*.cxx
""")

env.SharedLibrary('esoesaml2', [Glob(path) for path in paths])
